[DEFAULT]
model = Widar_ResNet18
dataset = widar
data_dir = ../data/
client_num_in_total = 30
client_num_per_round = 6
gpu_worker_num = 8
batch_size = 32
client_optimizer = sgd
lr = 1e-2
wd = 0.001
epochs = 1
fl_algorithm = fedaiot_distributed
comm_round = 300
test_frequency = 10
server_optimizer = sgd
server_lr = 1
alpha = 0.25
partition_type = uniform
device=cuda
trainer = BaseTrainer
amp = True
analysis= label_noise-0.05-0.005
entity=samiul
project=ray_fl_dev_v2
