[DEFAULT]
model = resnet18
dataset = epic_sounds
data_dir = ../data/
client_num_in_total = 30
client_num_per_round = 6
gpu_worker_num = 8
batch_size = 256
client_optimizer = sgd
lr = 1e-2
wd = 0.001
epochs = 1
fl_algorithm = fedaiot_distributed
comm_round = 100
test_frequency = 5
server_optimizer = sgd
server_lr = 1
alpha = 0.25
partition_type = central
device=cuda
trainer = BaseTrainer
amp = True
analysis= baseline
class_mixup=1.0
entity=fedaiot
project=ray_fl_dev_v3
