[DEFAULT]
model = CNNLSTM
dataset = ego4d
data_dir = ../data/
client_num_in_total = 30
client_num_per_round = 6
gpu_worker_num = 8
batch_size = 128
client_optimizer = sgd
lr = 1e-2
wd = 0.001
epochs = 1
fl_algorithm = fedaiot_distributed
comm_round = 1000
test_frequency = 2
server_optimizer = sgd
server_lr = 1
alpha = 0.25
partition_type = central
device=cuda
trainer = BaseTrainer
amp = False
analysis= baseline
entity=samiul
project=ray_fl_dev_v2
