[DEFAULT]
model = BiLSTMModel
dataset = casas
data_dir = ../data/
client_num_in_total = 50
client_num_per_round = 10
gpu_worker_num = 8
batch_size = 128
client_optimizer = sgd
lr = 1e-1
wd = 0.001
epochs = 1
fl_algorithm = fedaiot_distributed
comm_round = 300
test_frequency = 10
server_optimizer = sgd
server_lr = 1
alpha = 0.25
partition_type = dirichlet
device=cuda
trainer = BaseTrainer
amp = True
entity=samiul
project=ray_fl_dev_v2
