[DEFAULT]
model = LSTM_NET
dataset = wisdm
data_dir = ../data/
client_num_in_total = 30
client_num_per_round = 6
gpu_worker_num = 8
batch_size = 20
client_optimizer = sgd
lr = 0.01
wd = 0.001
epochs = 1
fl_algorithm = fedaiot_distributed
comm_round = 500
test_frequency = 5
server_optimizer = sgd
server_lr = 1
alpha = 0.25
partition_type = dirichlet
device=cuda
trainer = BaseTrainer
entity=samiul
project=ray_fl_dev_v2